export { default as Navigation } from './Navigation'

export { default as Home } from './home/Home'
export { default as Quotes } from './Quotes'
export { default as Couple } from './Couple'
export { default as Event } from './Event'
export { default as Map } from './Map'
export { default as Story } from './story/Story'
export { default as Gallery } from './Gallery'
export { default as Gift } from './gift/Gift'
export { default as Wishes } from './wishes/Wishes'
export { default as Closing } from './Closing'